CATEGORIES = [
    {
        "id": "caregiver",
        "img": "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&q=80",
        "title": "Caregiver",
        "emoji": "🤲",
        "color": "#FF8A3D",
        "badge": "Level 1",
        "stars": 1,
    },
    {
        "id": "basic",
        "img": "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=80",
        "title": "Basic Education",
        "emoji": "📓",
        "color": "#06D6A0",
        "badge": "Level 2",
        "stars": 2,
    },
    {
        "id": "graduate",
        "img": "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80",
        "title": "Graduate",
        "emoji": "🎓",
        "color": "#9B5DE5",
        "badge": "Level 3",
        "stars": 3,
    },
]

MODULES = [
    {
        "id": "study",
        "img": "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&q=80",
        "title": "Study English",
        "emoji": "📖",
        "color": "#118AB2",
        "icons": ["✏️", "📚", "🗣️"],
    },
    {
        "id": "work",
        "img": "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&q=80",
        "title": "Work Skills",
        "emoji": "🔨",
        "color": "#EF476F",
        "icons": ["🔧", "🏗️", "💼"],
    },
]

SCENARIOS = [
    {
        "id": "traffic",
        "img": "https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=800&q=80",
        "title": "Traffic",
        "emoji": "🚦",
        "color": "#FFD04E",
        "bg": "linear-gradient(160deg,#0f2027,#203a43,#2c5364)",
        "lessons": [
            {"word": "STOP", "phrase": "Please stop here.", "choices": ["STOP", "GO", "WAIT", "LEFT"]},
            {"word": "TURN", "phrase": "Turn left at the light.", "choices": ["TURN", "GO", "STOP", "CROSS"]},
            {"word": "WALK", "phrase": "Walk on the sidewalk.", "choices": ["WALK", "RUN", "DRIVE", "PARK"]},
            {"word": "SIGNAL", "phrase": "Use your signal light.", "choices": ["SIGNAL", "HORN", "BRAKE", "SPEED"]},
        ],
    },
    {
        "id": "school",
        "img": "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80",
        "title": "School",
        "emoji": "🏫",
        "color": "#06D6A0",
        "bg": "linear-gradient(160deg,#134e5e,#71b280)",
        "lessons": [
            {"word": "CLASS", "phrase": "The class starts at 8 AM.", "choices": ["CLASS", "LUNCH", "RECESS", "STUDY"]},
            {"word": "BOOK", "phrase": "Open your book to page 5.", "choices": ["BOOK", "PEN", "DESK", "CHAIR"]},
            {"word": "TEACHER", "phrase": "Ask the teacher for help.", "choices": ["TEACHER", "FRIEND", "GUARD", "PARENT"]},
            {"word": "LEARN", "phrase": "We learn something new today.", "choices": ["LEARN", "PLAY", "SLEEP", "EAT"]},
        ],
    },
    {
        "id": "grocery",
        "img": "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80",
        "title": "Grocery",
        "emoji": "🛒",
        "color": "#FF8A3D",
        "bg": "linear-gradient(160deg,#f7971e,#a05000)",
        "lessons": [
            {"word": "PRICE", "phrase": "What is the price of this?", "choices": ["PRICE", "SIZE", "COLOR", "WEIGHT"]},
            {"word": "CART", "phrase": "Put the items in the cart.", "choices": ["CART", "BAG", "BOX", "SHELF"]},
            {"word": "CHECKOUT", "phrase": "Go to the checkout line.", "choices": ["CHECKOUT", "ENTER", "EXIT", "WAIT"]},
            {"word": "RECEIPT", "phrase": "Keep your receipt.", "choices": ["RECEIPT", "CARD", "CASH", "CHANGE"]},
        ],
    },
    {
        "id": "retail",
        "img": "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=800&q=80",
        "title": "Retail",
        "emoji": "🏪",
        "color": "#EF476F",
        "bg": "linear-gradient(160deg,#c94b4b,#4b134f)",
        "lessons": [
            {"word": "HELP", "phrase": "Can I help you today?", "choices": ["HELP", "LEAVE", "WAIT", "LOOK"]},
            {"word": "RETURN", "phrase": "I would like to return this.", "choices": ["RETURN", "BUY", "KEEP", "SELL"]},
            {"word": "SIZE", "phrase": "Do you have this in my size?", "choices": ["SIZE", "COLOR", "STYLE", "BRAND"]},
            {"word": "SALE", "phrase": "This item is on sale.", "choices": ["SALE", "FULL", "GIFT", "FREE"]},
        ],
    },
    {
        "id": "hospital",
        "img": "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80",
        "title": "Hospital",
        "emoji": "🏥",
        "color": "#118AB2",
        "bg": "linear-gradient(160deg,#1a3a8f,#4a90d9)",
        "lessons": [
            {"word": "PAIN", "phrase": "I have pain in my chest.", "choices": ["PAIN", "COLD", "TIRED", "DIZZY"]},
            {"word": "DOCTOR", "phrase": "The doctor will see you now.", "choices": ["DOCTOR", "NURSE", "GUARD", "STAFF"]},
            {"word": "MEDICINE", "phrase": "Take this medicine twice a day.", "choices": ["MEDICINE", "FOOD", "WATER", "SLEEP"]},
            {"word": "EMERGENCY", "phrase": "This is an emergency!", "choices": ["EMERGENCY", "URGENT", "NORMAL", "WAIT"]},
        ],
    },
    {
        "id": "transport",
        "img": "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800&q=80",
        "title": "Transport",
        "emoji": "🚌",
        "color": "#9B5DE5",
        "bg": "linear-gradient(160deg,#360033,#0b8793)",
        "lessons": [
            {"word": "BUS", "phrase": "Which bus goes downtown?", "choices": ["BUS", "TRAIN", "TAXI", "BIKE"]},
            {"word": "TICKET", "phrase": "Please show your ticket.", "choices": ["TICKET", "CARD", "PASS", "COIN"]},
            {"word": "STOP", "phrase": "Next stop is Main Street.", "choices": ["STOP", "GO", "WAIT", "TURN"]},
            {"word": "STATION", "phrase": "Meet me at the station.", "choices": ["STATION", "AIRPORT", "PORT", "DEPOT"]},
        ],
    },
]
